name: Deploy to GitHub Pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '24'

            - name: Install dependencies
              run: npm install

            - name: Install dependencies
              run: npm install -g @angular/cli

            - name: Rebuild lightningcss
              run: npm rebuild lightningcss

            - name: Build apps
              run: npm run build:apps

            - name: Copy CNAME and README files
              run: |
                apps=(
                  ngx-datetime-app
                  ngx-core-app
                  ngx-app
                  ngx-ace-app
                  ngx-fabric-app
                  ngx-http-app
                  ngx-crud-app
                  ngx-socket-app
                  ngx-rtc-app
                  ngx-translate-app
                  ngx-tinymce-app
                  ngx-ui-app
                )

                for app in "${apps[@]}"; do
                  cp "projects/$app/CNAME" "dist/$app/browser/"

                  package_name="${app%-app}"
                  readme_path="projects/$package_name/README.md"

                  if [ -f "$readme_path" ]; then
                    cp "$readme_path" "dist/$app/browser/"
                  fi
                done

            - name: Set up SSH
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Deploy apps to gh-pages using SSH
              env:
                  GIT_SSH_COMMAND: 'ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'
              run: |
                  apps=(
                    ngx-datetime-app
                    ngx-core-app
                    ngx-app
                    ngx-ace-app
                    ngx-fabric-app
                    ngx-http-app
                    ngx-crud-app
                    ngx-socket-app
                    ngx-rtc-app
                    ngx-translate-app
                    ngx-tinymce-app
                    ngx-ui-app
                  )

                  for app in "${apps[@]}"; do
                    domain="${app%-app}.webart.work"

                    pushd "dist/$app/browser"
                    git init
                    git add --all .
                    git commit -m "Deploy to GitHub Pages"
                    git checkout -B gh-pages
                    git push "git@github.com:WebArtWork/$domain" gh-pages --force
                    popd
                  done

            - name: Clean up SSH
              run: |
                  rm -f ~/.ssh/id_rsa
                  rm -f ~/.ssh/known_hosts
